name: Generate Task plots

on:
  push:
    paths:
      - "logs/**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-plots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas matplotlib seaborn

      - name: Generate summary CSV
        run: |
          python scripts/generate_summary_csv.py --num-bins 3

      - name: Generate SSM plots
        run: |
          python scripts/update_ssm_plots.py --arch olmossm


      - name: Prepare website
        run: |
          mkdir -p site/plots

          cp -r plots/* site/plots/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4